### ISSUE TITLE
EnderIO Soulbound enchantment

### ISSUE THREAD

**Issue by Ksnz** [TCPR/Thermos#177] opened 2016-02-28 16:38 UTC
> Items with this enchantment will not be dropped when the player dies.

![2016-02-28_19 33 25](https://cloud.githubusercontent.com/assets/3342111/13380360/27a0a7d2-de52-11e5-9ace-36052fe0c928.png)
Sword still here
![2016-02-28_19 33 40](https://cloud.githubusercontent.com/assets/3342111/13380362/2d69c5c2-de52-11e5-8439-64a8f074870d.png)
But now it disappears
![2016-02-28_19 33 59](https://cloud.githubusercontent.com/assets/3342111/13380363/31186552-de52-11e5-9705-eb5e8dded385.png)

**Comment by bookerthegeek** [comment] 2016-02-28 19:08
What mod adds the soulbound you are using?

**Comment by Razorskills** [comment] 2016-02-28 19:14
The name of the issue says EnderIO.

**Comment by bookerthegeek** [comment] 2016-02-28 19:14
Derp.

**Comment by Razorskills** [comment] 2016-02-28 19:20
The issue also could be related to these:
https://gitlab.prok.pw/KCauldron/KCauldron/issues/196
https://gitlab.prok.pw/KCauldron/KCauldron/issues/301
I leave those there in case they are helpful.

**Comment by Ksnz** [comment] 2016-02-28 21:50
@bookerthegeek EnderIO-1.7.10-2.2.8.381
Thermos-1.7.10-1614.32-server-beta.jar

**Comment by tyler2k15** [comment] 2016-03-02 14:47
Duplicate of #118

**Comment by Robotia** [comment] 2016-03-02 19:41
Should be fixed in BL35

**Closed** 2016-03-03 04:00 UTC
