### ISSUE TITLE
[Mod Incompatibility] Inventory Clear on Respawn with keepInventory True

### ISSUE THREAD

**Issue by Eufranio** [TCPR/Thermos#236] opened 2016-03-13 18:36 UTC
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
Are no logs for this, on client and the server.

**Explanation of issue:**
I have keepInventory true on my server, but i'm having an problem with him today. When an player dead, your inventory don't clear. But when he click on "Respawn" button after death, your inventory is cleaned. No logs, only the error. This happened after i update to the Thermos 1614.46.

**Thermos Version:**
1.7.10-1614.46

**Comment by Robotia** [comment] 2016-03-13 19:19
O.o will investigate

**Comment by Robotia** [comment] 2016-03-14 03:01
One of the users on Discord tested this and found that this is not the case. Are you certain you were not using an outdated version or that this is a mistake on your part?

**Comment by djoveryde** [comment] 2016-03-14 10:15
I've tested and inventory is kept fine on the overworld after typing the keepInventory true.

However @Eufranio double check this player is not dying in other worlds as you have to set keepInventory to true on each world by going to that world and issuing the command.

@Robotia I thought at one point keepInventory defaulted to all worlds? Could be wrong.
Perhaps is there a way to add a "/Gamerule keepInventoryAll" so it flags to keep inventory on all worlds for those that want inventory kept globally?

**Comment by Robotia** [comment] 2016-03-14 12:45
That's definitely doable but I'd rather add it as a cauldron configuration, if it were a game rule, few people would actually know such a feature exists

**Comment by Eufranio** [comment] 2016-03-14 17:39
The players are not losing your inventories, by default. When they dead, your hotbar still with the items (the items aren't dropped). The problem is when they click on "Respawn" button, your items now are cleaned... I'm using latest stable version from Thermos, and this issue is happening after update.

**Comment by Robotia** [comment] 2016-03-14 18:03
@Eufranio I'm thinking this is caused by one of your modpacks...what packs do you have?

**Comment by Eufranio** [comment] 2016-03-14 18:24
I have an pack that myself created. I'm not thinking that is about the pack, because i never had this problem, happened just when i updated thermos for the latest version.

**Comment by Robotia** [comment] 2016-03-14 18:32
@Eufranio You have keepInventory enabled on every world as @djoveryde mentioned, correct?
Also, could you try this on a test server with most of the mods from your pack removed? Since I have reports from 2 people on Discord now that this is not happening for them, I want to determine if it is a mod-specific incompatibility

**Comment by Eufranio** [comment] 2016-03-14 20:53
Yep, i have keepInventory true on all worlds. And i tested without mods, seems fine. Maybe could be an mod incompatibility, i'll test with some mods now.

**Comment by Robotia** [comment] 2016-03-14 22:48
@Eufranio thank you :smile:

**Comment by Eufranio** [comment] 2016-03-14 22:50
I really don't know what mod is causing the issue... The only mod that change player inventories after death is OpenBlocks, but it's not even spawning the gravestone...

**Comment by Robotia** [comment] 2016-03-14 22:58
@Eufranio when players die, do they respawn in a different dimension?

**Comment by Eufranio** [comment] 2016-03-14 23:02
Yep, they spawn on server hub.

**Comment by djoveryde** [comment] 2016-03-14 23:17
@Eufranio Do you have Multiverse plugin loaded on that server at all?

**Comment by Eufranio** [comment] 2016-03-15 00:22
No, i'm using multiworld (that plugin add dimensions).

**Comment by Robotia** [comment] 2016-03-15 02:59
Issue likely deals with the calling of dimension change and respawn events.

**Comment by Eufranio** [comment] 2016-03-15 03:02
I tested now, and when player death on another dimension (excluding overworld), then gravestone spawns with your inventory. But when they dead on overworld, the grave dont spawn and player lose your items.

**Comment by Robotia** [comment] 2016-03-15 03:21
@Eufranio the respawn and dimension events are out of order then, fixing now.

**Comment by Bogdan-G** [comment] 2016-03-15 12:14
mod AoA work breaks keepInventory, Xolova wontfix it.

**Comment by Eufranio** [comment] 2016-03-15 12:35
I'm not using AoA.

**Comment by Eufranio** [comment] 2016-03-15 16:33
Tested with latest build, still bugging. (clear after click on respawn)

**Comment by djoveryde** [comment] 2016-03-15 17:03
What plugins/Mods do you have, its odd how no one can reproduce this error. If I can have a list of all mods & plugins you have I can test this for you.

**Comment by Eufranio** [comment] 2016-03-15 17:07
My modpack is on technic: http://api.technicpack.net/modpack/magitech-server-1710
Plugins (40): Itemizer, dynmap, WorldEdit, FrameProtect, Better_AntiSpam, OpenInv, Essentials, Offline_Teleporter, LoginSecurity, ClearLag, PlugMan, DMotd, SleepPercentage, EasyBackup, CustomShutdown, WorldGuard, DKLib, ProtocolLib, MyItems, AutoSaveWorld, MultiWorld, KitAdder, PermissionsEx, BanItem, NoteBlockAPI, Whitelist, MyMenu, Vault, EssentialsSpawn, MyCommand, TitleManager, AutoIn, ChestShop, NoteBlockPlayer, ScoreboardStats, Trading, WarpPortals, Citizens, Legendchat, CommandNPC

**Comment by Eufranio** [comment] 2016-03-15 18:33
@Robotia , can you public an build that keepInventory for thermos bypass forge? I think that is the unique solution...

**Comment by Robotia** [comment] 2016-03-15 19:16
I do not understand what you are asking for, are you saying never notify mods that a respawn event occurs?

**Comment by Eufranio** [comment] 2016-03-15 19:42
Yep. So, when an player dead, he will respawn with vanilla presets, and it's not bugging.

**Comment by Robotia** [comment] 2016-03-15 21:08
I can give you something specifically for that...but it will not be updated.

**Comment by Eufranio** [comment] 2016-03-15 23:00
Yes :D while using your specific verwion, i will try find what the causes of the problem.

**Comment by Eufranio** [comment] 2016-03-16 01:34
Unloading the multiworld dimension (Server hub) seems resolved the problem. Now keepIventory is working. I think that's an plugin incompatibility...

**Comment by djoveryde** [comment] 2016-03-16 09:34
Similar to Multiverse issue then. What version of Multiworld are you using? 
Try using the next version down (IE. If your using 5.2.6 try using 5.2.5).
If you are using 5.2.7 that version is for 1.8 only and would cause problems.

**Comment by Eufranio** [comment] 2016-03-16 10:39
I tried the three latest versions above 5.2.7 from Bukkit, and error persists. I still thinking that is an incompatibility.

**Closed** 2016-03-16 10:42 UTC

**Comment by Eufranio** [comment] 2016-03-16 16:58
Sugestion: Add an option on thermos config that allow players that dead respawn on same world (overworld), not on the server real spawn.

**Comment by Robotia** [comment] 2016-03-16 18:30
That is caused by one of your plugins, it is not our fault.

**Comment by Bogdan-G** [comment] 2016-03-17 09:58
We have repeatedly made compatible with anything on the side of the cauldron for the slaves of something else.
