### ISSUE TITLE
Issue with LegendQuest 1.9.7 & Thermos

### ISSUE THREAD

**Issue by DraksterAU** [TCPR/Thermos#242] opened 2016-03-15 06:32 UTC
Issue being experienced with LegendQuest still seems to relate to Autonomous Activators being treated as real players by bukkit plugins, see below;

NOTE: This happens with or without PWP installed.

EDIT : **Using Latest Thermos version, B48.**

```

Could not pass event PlayerInteractEvent to LegendQuest v1.9.7
org.bukkit.event.EventException
        at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:118) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.49]
        at me.incomprehendable.dev.pwp.transparentlisteners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:28) [PerWorldPlugins.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.49]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.49]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:223) [CraftEventFactory.class:1.7.10-1614.49]
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:239) [ForgeEventFactory.class:1.7.10-1614.49]
        at cofh.thermalexpansion.block.device.TileActivator.simRightClick2(TileActivator.java:434) [TileActivator.class:?]
        at cofh.thermalexpansion.block.device.TileActivator.simRightClick(TileActivator.java:401) [TileActivator.class:?]
        at cofh.thermalexpansion.block.device.TileActivator.doDeploy(TileActivator.java:217) [TileActivator.class:?]
        at cofh.thermalexpansion.block.device.TileActivator.func_145845_h(TileActivator.java:176) [TileActivator.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2548) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:976) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
        at me.sablednah.legendquest.playercharacters.PC.getLoadout(PC.java:2233) ~[?:?]
        at me.sablednah.legendquest.playercharacters.PC.getLoadout(PC.java:2227) ~[?:?]
        at me.sablednah.legendquest.listeners.SkillLinkEvents.onInteract(SkillLinkEvents.java:61) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor112.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
        at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:116) ~[?:?]
        ... 17 more


```

**Comment by Robotia** [comment] 2016-03-15 06:40
Please note the Thermos version like asked for in the default template.

**Comment by DraksterAU** [comment] 2016-03-15 06:41
@Robotia Sorry mate, I'm using B48.

**Comment by Yive** [comment] 2016-03-16 08:55
Seems to be a compatibility issue with PerWorldPlugins. I highly recommend against using plugins like that, they usually cause a lot of issues, even on non modded server.

**Comment by DraksterAU** [comment] 2016-03-16 09:27
@Yive it happens with or without PwP installed.

**Comment by djoveryde** [comment] 2016-03-16 10:25
By the look of it the issue is with copatibility between LegendQuest and PwP

**Comment by DraksterAU** [comment] 2016-03-16 10:29
@djoveryde Autonomous activators run on a schedule on my server to automatically restart admin created computers when they crash.

Thermos is treating the thermal expansion activator as a real player and causing legend quest to process the interaction as if it was a real player.

Per world plugins does NOT come into play with this issue - the issue happens even when it is not installed.

**Comment by djoveryde** [comment] 2016-03-16 10:33
Could this be an issue with the way Bukkit/Forge Events are handled now?
As seems its an issue between a Mod and a plugins Event?

**Comment by DraksterAU** [comment] 2016-03-16 11:36
Not yet. He knows his stuff and will close this off when he is confident it is fixed (or it is decided it won't be). 
I'll test shortly.

**Comment by Robotia** [comment] 2016-03-17 02:32
@DraksterAU On a test server, could you please try doing `/cauldron debug`, running a tile activator, and letting me know what debug output you get?

**Comment by DraksterAU** [comment] 2016-03-17 02:57
Will try tonight :)

**Comment by Robotia** [comment] 2016-03-30 22:38
Fixed by https://github.com/TCPR/Thermos/commit/b0466098838484038c5ed6a7dd7e8ba49386d85a

**Closed by Robotia** 2016-03-30 22:38 UTC

**Comment by DraksterAU** [comment] 2016-03-30 23:24
@robotia sorry man I completely spaced about this one....

**Comment by Robotia** [comment] 2016-03-31 15:42
It's fine :sunglasses:
