### ISSUE TITLE
[BUG] Weather is changing too quickly

### ISSUE THREAD

**Issue by CovehiH** [TCPR/Thermos#161] opened 2016-02-26 11:07 UTC
You can try to change the weather in a singleplayer and server. Server has no effects of changing weather. Сlouds appear and begins to rain at once. Checked without mods and plugins.

30b of thermos

**Comment by spannerman79** [comment] 2016-02-26 11:14
https://github.com/TCPR/Thermos/releases/tag/32

**Comment by CovehiH** [comment] 2016-02-26 12:44
No changes with last buiid..

**Comment by Robotia** [comment] 2016-02-26 15:25
Are you certain? Weather seems to be fine (everyone complained on my server when I did `/toggledownfall`).

**Comment by CovehiH** [comment] 2016-02-26 16:05
Yes I am sure. Is not modpack. Nude Thermos with default configs.
Perhaps you do not understand me.Try compare the effects in singleplayer and server before the coming of rain - they are all different. On the server, it comes almost at once  but in a SP is slow and accompanied with effects.

**Comment by Robotia** [comment] 2016-02-26 17:11
Ok, then this definitely needs investigation. Have you tried a vanilla forge server?

**Comment by CovehiH** [comment] 2016-03-02 07:50
Yes! On vanilla forge issue does not seen

**Comment by Robotia** [comment] 2016-03-09 05:41
@CovehiH Ok I think I can see why...Cauldron removed sending information about rain in WorldServer.updateWeather(), breaking a Forge behavior. Reverting now.

**Comment by Robotia** [comment] 2016-03-09 05:42
@CovehiH This information was *never* sent, so that would explain why rain would appear suddenly
```java
        if (this.prevRainingStrength != this.rainingStrength)
        {
            this.mcServer.getConfigurationManager().sendPacketToAllPlayersInDimension(new S2BPacketChangeGameState(7, this.rainingStrength), this.provider.dimensionId);
        }

        if (this.prevThunderingStrength != this.thunderingStrength)
        {
            this.mcServer.getConfigurationManager().sendPacketToAllPlayersInDimension(new S2BPacketChangeGameState(8, this.thunderingStrength), this.provider.dimensionId);
        }
```

**Comment by Ghostlyr** [comment] 2016-03-09 08:26
I can confirm problem is fixed on 46 build. Great job!

**Comment by CovehiH** [comment] 2016-03-09 09:00
Oh! Thanks!

**Closed** 2016-03-09 11:02 UTC
