### ISSUE TITLE
[Warning] Don't use ANY tick limiting

### ISSUE THREAD

**Issue by Robotia** [TCPR/Thermos#52] opened 2016-01-31 00:07 UTC
TickProfiler is the bane of KCauldron's existence, and as noted by #51 , causes problems. It gives useless results because KCauldron lowers the tickrate for stuff when players are far away

@spannerman79 has brought to my attention the fact that Spigot's tick limiter is the bane of just about every mod's existence.

Alternatives Include:
+ Get Bukkit's ClearLag and occasionally run `/lagg killmobs` to get rid of mobs
+ Edit settings in `tileentities.yml`
+ Optimize your mob spawning settings in `spigot.yml` and `bukkit.yml`
+ Get a real profiler: `VisualVM`, `YourKit`, and `WarmRoast` are great choices

**Comment by Robotia** [comment] 2016-01-31 00:14
I just realized I still had it on one of my test servers and found it causing the server to lag with *no players online*. Again, I highly recommend you get rid of it.

**Comment by iKaneki-Ken** [comment] 2016-01-31 02:32
Did someone come here asking for you to fix the issue with TickProfiler?

**Comment by Yive** [comment] 2016-01-31 02:37
It's recommended to added a patch similar to the one that Spigot did when EchoPets caused it to crash on boot. The class pretty much just stopped the plugin from loading at all.

**Comment by spannerman79** [comment] 2016-01-31 14:52
> Spigot limits the maximum time a tile-entity can "tick", so no specific tile / entity will lag the server

Its broken http://aikar.co/2015/10/08/spigot-tick-limiter-dont-use-max-tick-time/ don't use it

**Comment by Robotia** [comment] 2016-01-31 16:34
@spannerman79 Did not realize this updating this post now.

**Comment by spannerman79** [comment] 2016-01-31 16:45
Not many do, and in fact what @Yive did at https://github.com/TCPR/KCauldron/commit/63564ff3e99218e9cbab60cea8ae13eaf09e56e3 was correct on every count.

Most don't understand that the settings that was in dispute from @Bogdan-G that it doesn't cut the gameplay and yourself @Robotia  were in fact spawn rates **per connected user**, not server overall and other bugs that weren't fixed in Spigot 1.7.10 which we all know that KCauldron uses.  Only "easy" way to fix Tick-Limiting is to set `max-tick-time.tile` & `max-tick-time.entity` to `1000` - effectively disabling the broken Spigot Tick Limiting.

**Comment by spannerman79** [comment] 2016-01-31 17:00
In fact if people want to have a better dynamic tick system take a look at @wildex999 mod TickDynamic https://github.com/wildex999/TickDynamic

**Comment by Bogdan-G** [comment] 2016-01-31 17:19
@spannerman79 I made a change in tick-limiter in his mustache to check `==` on `! =`, as it did in October spigot patch.

**Comment by nallar** [comment] 2016-02-06 13:11
Is there a simple way I can reproduce the issue?

Which KCauldron and TickProfiler builds are being used?

**Comment by nallar** [comment] 2016-02-06 13:37
The TE list cleanup code here: https://github.com/TCPR/Thermos/blob/master/patches/net/minecraft/world/World.java.patch#L931 is conflicting with TP's hook and resulting in the TE list being emptied if a TE is unloaded while ticking.

If a TE is unloaded while TP profiling is running, that will replace the loaded TE list with an empty list, resulting in everything stopping ticking, matching the report above.

> I just realized I still had it on one of my test servers and found it causing the server to lag with no players online. Again, I highly recommend you get rid of it.

I can't replicate slow performance just from having TP installed - don't really understand how that would happen, as TP does almost nothing when not profiling. It only installs hooks when profiling is started. Can you share a sampling snapshot?

Why does the cleanup code copy into a new list, instead of using an iterator and calling `iterator.remove()` if `marker` is `false`?

**Comment by nallar** [comment] 2016-02-06 14:00
Saw the commit message for 2e860900236bb80f8106789775d69801b28b5db9 explaining reasoning.

Do you know what JRE version you saw poor removeAll performance on? In extremely old versions (anything older than JRE 6u15) it wasn't specialised and called remove(value) for each value in the passed collection, which was incredibly slow.

On any up-to-date JRE it has much better performance, and is definitely faster than creating a new list. See https://bugs.openjdk.java.net/browse/JDK-6529800

**Comment by iKaneki-Ken** [comment] 2016-02-06 16:32
Omg, it's @nallar! Hai nallar! :D

**Comment by nallar** [comment] 2016-02-09 15:50
New TickProfiler builds should now work with Thermos. If anyone wants to test, they can add `-Dthermos.tickprofiler.disable=false` before the `-jar` in their launch script to allow TickProfiler to load.

**Comment by Robotia** [comment] 2016-02-09 16:00
Thanks nallar, this is awesome! If it works out, I'll remove the code that prevents it from loading asap.

**Comment by iKaneki-Ken** [comment] 2016-02-09 16:31
@nallar I noticed that you've recently pushed some commits to TickThreading, I thought you dropped TickThreading altogether?

**Comment by nallar** [comment] 2016-02-09 16:32
@iKaneki-Ken https://github.com/nallar/TickThreading/issues/1248

**Comment by iKaneki-Ken** [comment] 2016-02-09 16:44
@nallar Oh thank you! And thank you for picking up TickThreading again! 1.7.10 has been hell trying to optimize it. I now actually look forward to actually playing Minecraft 1.8.9 on my server because of this.

**Closed** 2016-02-17 03:21 UTC
Labels: wontfix
