### ISSUE TITLE
Inventory Wipe on Death and Dimension Switch.

### ISSUE THREAD

**Issue by iKaneki-Ken** [TCPR/Thermos#55] opened 2016-02-01 12:51 UTC
When I upgraded to build 13 of (K)Cauldron, while you have keepInventory set to true in any world, if you switch from a dimension with keepInventory on to a dimension without it on, it causes the players inventory to be wiped.

Now while there is an easy fix by turning off keepInventory, just thought I'd report the issue.

Thank you Robotia, keep up the awesome work! Performance and stability keeps improving!

**Comment by Robotia** [comment] 2016-02-01 14:21
@iKaneki-Ken This didn't happen with release 12, correct?

**Comment by iKaneki-Ken** [comment] 2016-02-01 14:27
Haven't tested Build 12, upgraded from build 3 to build 13. I will use build 12 as soon as possible.

**Comment by Yselith** [comment] 2016-02-01 15:16
I have this issue with 12 and 13

**Comment by Robotia** [comment] 2016-02-01 15:22
@Yselith and @iKaneki-Ken , know if it happened with build 3?

**Comment by Robotia** [comment] 2016-02-01 15:25
This is related to #39 probably caused by the fix for that.

**Comment by iKaneki-Ken** [comment] 2016-02-01 15:26
@Robotia Nope, never happened in B3, only started happening when B13 was used.

**Comment by Robotia** [comment] 2016-02-01 15:49
Ok it is indeed related to #39 then

**Comment by Robotia** [comment] 2016-02-01 22:35
@iKaneki-Ken When B14 is out, close this issue if it no longer persists.

**Comment by Robotia** [comment] 2016-02-02 00:36
@iKaneki-Ken Had to revert this plus a bunch of KC fixes, turns out they have horribly broken permissions.

**Comment by iKaneki-Ken** [comment] 2016-02-02 08:15
Personally not surprised. Thank you for the really quick fix Robotia!

**Comment by Robotia** [comment] 2016-02-02 17:47
@iKaneki-Ken Yeah the initial Cauldron is built on a now unsupported version of Forge :confused:

**Comment by Robotia** [comment] 2016-02-02 17:53
@iKaneki-Ken Hmm...seems to deal with the fact that the code considers the *current world's* keepInventory config. Going to try changing the order of dimension change and respawn, see if that works better.

**Comment by Robotia** [comment] 2016-02-05 20:19
Did build 14 fix this?

**Comment by iKaneki-Ken** [comment] 2016-02-05 20:53
No, build 14 didn't fix this. This also only happens after we turn keepInventory true in dimension 0 as well.

**Comment by iKaneki-Ken** [comment] 2016-02-06 21:41
Wasn't fixed in the latest build. Sorry for about being annoying. >_<

**Comment by TerdyTheTerd** [comment] 2016-02-07 05:57
@Robotia Looks like this goes hand in hand with my new issue. I found that in build 16 using commands to teleport across dimensions keeps inventory with <code>gamerule keepInventory false</code> in both world, however using build 17 and up, with the same <code>gamerule keepInventory false</code> results in the player inventory being wiped using commands to teleport. Using in-game portals works as expected (I used the nether in this example).

I did also test using KCauldron, both of their newest versions do not have this issue.

**Comment by Robotia** [comment] 2016-02-07 06:29
@TerdyTheTerd Are you certain? I am using B20, teleporting from world to world with Essentials does not affect player inventories.

**Comment by TerdyTheTerd** [comment] 2016-02-07 06:30
0.o Build 20 wasn't showing up when I had tested this, will go and test right away!

**Comment by Robotia** [comment] 2016-02-07 06:33
@TerdyTheTerd That shouldn't make a difference sadly :confused:

**Comment by TerdyTheTerd** [comment] 2016-02-07 07:10
Sorry for the video quality, youtube felt like down sampling it cuz the frame was slightly less than standard 1920x1080. [Video](https://www.youtube.com/watch?v=jRyj5DT1WZw&feature=youtu.be)

**Comment by iKaneki-Ken** [comment] 2016-02-08 21:28
Someone on my server just lost their inventory teleporting from the Nether to the main world.

One thing I'm noticing is it's more likely to happen to players that carry a massive amount of items in the bags.

As well, players that use the portal that the Ender Dragon spawns on death lose their inventory 100% of the time.

**Comment by Robotia** [comment] 2016-02-08 22:11
@iKaneki-Ken I will fix this as soon as I can, sorry that this is an issue. Revert to S13 for now.

**Comment by djoveryde** [comment] 2016-02-11 10:53
I will admit, and im not sure if theres a fix for it but for my server if a player stores a bag within a bag eventually their player data becomes corrupt due to the amount of data stored. Is there a way to prevent the player corruption?

**Comment by Robotia** [comment] 2016-02-11 14:03
Please share the error log

**Comment by iKaneki-Ken** [comment] 2016-02-11 17:24
@djoveryde No there isn't. Everything has limits, and mod devs warn players not to do stuff like that.

**Comment by Robotia** [comment] 2016-02-11 19:32
I can create a mini algo that will reset player locations to the spawn if they log in/out in under a second two times in a row.

**Comment by iKaneki-Ken** [comment] 2016-02-11 19:35
@Robotia That would actually be awesome, would get rid of the command I had to code in that teleports people to spawn on login.

**Comment by Robotia** [comment] 2016-02-11 21:00
Closing and re-creating separate issue for this discussion.

**Closed by Robotia** 2016-02-11 21:00 UTC
