### ISSUE TITLE
[Crash] NOMOD NAME - NO ERROR Occur

### ISSUE THREAD

**Issue by gafunbird007** [TCPR/Thermos#186] opened 2016-03-01 18:57 UTC
my server randomly no responding sometime with no pattern and no log and error it just freezing and no response here is it happen after i install aether ii also it happen with KCauldron too i have no idea what it cause from.
My LOG : http://www.mc-baby.in.th/2559-03-01-7.log

**Comment by NEXUS2345** [comment] 2016-03-01 21:38
First of all, please never leave a server longer than 6 hours without restarting it. Most hosting companies have a system to allow you to schedule restarts, and Multicraft and McMyAdmin both have facilities to do so too.

Second of all, to find the cause you will need to do the following. Download Sampler from sfPlayer here: http://files.player.to/sampler-1.59.jar and install it into your server's mods folder.
It will generate something called a stall report when the server freezes for a certain amount of time. Once one is produced, please post the contents here so we can assist you.

**Comment by Robotia** [comment] 2016-03-01 22:05
@gafunbird007 https://github.com/TCPR/Thermos/releases/download/untagged-069baaa40387929c03f5/Thermos-1.7.10-1614.UNOFFICIAL-server.jar

**Comment by gafunbird007** [comment] 2016-03-01 23:08
Al right thank you verymuch for all your help

**Comment by enterprise12nx** [comment] 2016-03-02 00:31
@Robotia is that a stable version? i am still using B23 as its been most stable

**Comment by gafunbird007** [comment] 2016-03-02 01:04
@robotia you mean you want me to using that build right

**Comment by Robotia** [comment] 2016-03-02 01:27
@gafunbird007 yes

**Comment by gafunbird007** [comment] 2016-03-02 01:37
Thankyou very much I will try and post the result here

**Comment by gafunbird007** [comment] 2016-03-02 01:39
@nexus2345 I have my own server do you have any plugin to auto restart server

**Comment by Robotia** [comment] 2016-03-02 01:59
@gafunbird007 Infinite uptime script (auto up on crash)
```bash
while :
do
java -d64 -server -XX:+UseG1GC -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:MetaspaceSize=1024m -XX:MaxMetaspaceSize=2048m  -XX:+AggressiveOpts -XX:MaxGCPauseMillis=10 -XX:+UseStringDeduplication -Xms8G -Xmx12G -noverify -XX:hashCode=5 -Dfile.encoding=UTF-8 -jar Thermos.jar nogui --log-strip-color
sleep 2
done

```

**Comment by vadimyer** [comment] 2016-03-02 02:31
@Robotia Thermos-1.7.10-1614.UNOFFICIAL-server.jar - what's that?

**Comment by vadimyer** [comment] 2016-03-02 02:37
@gafunbird007 I've had random freezes in the past because of too many unknown (to me) Java  switches. I don't understand them at all, so I've just cut all the switches except -Xmx and freezes of that kind were gone.

Now I just rarely get freezes of a kind where the server stops responding, but chat is working, and after that server actually stops and logs contain some information like that:
```
------------------------------
[21:35:26] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: Current Thread: Thread-8
[21:35:26] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 	PID: 24 | Suspended: false | Native: false | State: TIMED_WAITING
[21:35:26] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 	Stack:
[21:35:26] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		java.lang.Thread.sleep(Native Method)
[21:35:26] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		buildcraft.BuildCraftMod$PacketSender.run(BuildCraftMod.java:127)
[21:35:26] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		java.lang.Thread.run(Thread.java:745)
[21:35:26] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: ------------------------------
[21:35:26] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: ------------------------------
[21:35:26] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: Current Thread: Thread-7
[21:35:26] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 	PID: 21 | Suspended: false | Native: false | State: WAITING
[21:35:26] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 	Stack:
[21:35:26] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		sun.misc.Unsafe.park(Native Method)
[21:35:26] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
[21:35:26] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
[21:35:26] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
[21:35:26] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		com.mojang.util.QueueLogAppender.getNextLogEvent(QueueLogAppender.java:77)
[21:35:26] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		org.bukkit.craftbukkit.v1_7_R4.util.TerminalConsoleWriterThread.run(TerminalConsoleWriterThread.java:25)
[21:35:26] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 		java.lang.Thread.run(Thread.java:745)
[21:35:26] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: ------------------------------
[21:35:26] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: ------------------------------
[21:35:26] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: Current Thread: DestroyJavaVM
[21:35:26] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 	PID: 19 | Suspended: false | Native: false | State: RUNNABLE
[21:35:26] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: 	Stack:
[21:35:26] [AutoSaveWorld CrashRestartThread/ERROR] [Minecraft/]: ------------------------------
```

**Comment by gafunbird007** [comment] 2016-03-02 03:03
@Robotia  is it gonna work with my problem because the server is not stop but it just no response and freezing like that forever

**Comment by gafunbird007** [comment] 2016-03-02 04:19
@Robotia  That build have a bug when ever player teleport to other world it clear all item in inventory out

**Comment by Robotia** [comment] 2016-03-02 04:37
You are right this is a bug with the spigot watchdog which should force the server to stop in that case

**Comment by gafunbird007** [comment] 2016-03-02 04:42
@Robotia  is there any libraries file for the build that you gave me

**Comment by Robotia** [comment] 2016-03-02 04:47
Libraries should be the same

**Comment by gafunbird007** [comment] 2016-03-02 05:04
@Robotia  There is a bug for that build you gave me and the b34 too which is when every you move the world your inventory will be clear

**Comment by gafunbird007** [comment] 2016-03-02 06:13
@vadimyer thankyou for your help i will try but here is what happen to me 
Picture : www.mc-baby.in.th/show.png

**Comment by vadimyer** [comment] 2016-03-02 06:17
I was in your situation. Removing switches except -noverify and -Xmx should help, also, if sampler is installed and the server crashes, it stores a "log" in a folder, if I recall, "stall-reports", but that's not your case, just guessing.

**Comment by gafunbird007** [comment] 2016-03-02 06:22
@vadimyer 
java -server -d64 -XX:+UseG1GC -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:MetaspaceSize=2G -XX:MaxMetaspaceSize=4G  -XX:+AggressiveOpts -XX:MaxGCPauseMillis=10 -XX:+UseStringDeduplication -Xms18G -Xmx23G -XX:hashCode=5 -noverify -Dfile.encoding=UTF-8 -jar Thermos-1.7.10-1448.30-server.jar --log-strip-color

So just change it to
java  -Xmx23G -noverify -Dfile.encoding=UTF-8 -jar Thermos-1.7.10-1448.30-server.jar ??

**Comment by vadimyer** [comment] 2016-03-02 06:25
@gafunbird007 Yeah. 2) Yeah too, but I don't know how to read that "log", there should be a program for visualizing it, someone told the highest stack in that "log" is most likely the problem. Again, I don't think this is your case.

**Comment by gafunbird007** [comment] 2016-03-02 15:52
@nexus2345 @robotia it happen again and here is my stall report : www.mc-baby.in.th/stall.txt

**Comment by Robotia** [comment] 2016-03-02 19:42
Determined to be a non-Thermos issue, fixed by editing Aether mod code.

**Closed by Robotia** 2016-03-02 19:42 UTC
