### ISSUE TITLE
[Crash] Biomes O' Plenty - net.minecraft.util.ReportedException: Exception getting block type in world

### ISSUE THREAD

**Issue by AlphaModder** [TCPR/Thermos#143] opened 2016-02-23 22:15 UTC
I'm trying to set up an almost-FTB Infinity server (has worldedit and voxelsniper) with Thermos, but when I switch the world type to BIOMESOP, the server crashes while generating the world. 

[Crash](http://pastebin.com/dtrQcYzb)

[Mods](http://pastebin.com/WnRztGeD)

[Plugins](http://pastebin.com/hSj7pG0D)

[Full Server Log](http://paste.feed-the-beast.com/view/756aabdd) (It was too big for pastebin.)

**Comment by Robotia** [comment] 2016-02-23 23:36
Another issue caused by the custom block updates tracker, will be fixed ~ Friday

**Comment by AlphaModder** [comment] 2016-02-24 01:26
@Robotia I'm guessing from the log that it doesn't handle block changes with null for the block, maybe? Idk.

**Comment by Robotia** [comment] 2016-02-24 01:38
Basically, we implemented something from KCauldron a while back that we never should have. It'll take a few hours to go through and scrape it out

**Comment by spannerman79** [comment] 2016-02-24 01:43
Not sure if you want to head this direction but you might want to consider going right back to the commit point of KCauldron build 152 and go forward from there.

I actually found that build 152 and Open Modular Turrets doesn't have [this](https://gitlab.prok.pw/KCauldron/KCauldron/issues/275) issue - obviously changing the forge submodule to https://github.com/MinecraftForge/MinecraftForge/commit/c6aa04325e8a80af88755adb2339a402e7e90ebb as well helps

**Comment by Robotia** [comment] 2016-02-24 01:58
@spannerman79 It will be a nightmare to go through all the commits for that :/

**Comment by Robotia** [comment] 2016-02-24 02:01
And we are already up to date on the forge submodule, `git pull origin 1.7.10` returns up-to-dat

**Closed** 2016-02-24 02:13 UTC
