### ISSUE TITLE
Thermos Build 50 & Carpenters Blocks

### ISSUE THREAD

**Issue by djoveryde** [TCPR/Thermos#261] opened 2016-03-21 17:41 UTC
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/yjMsYD1S

**Explanation of issue:**
Since updating to Build 50 players now crash whenever they try to go to their base with the above error. The issue never occurred when running build 45.
This shows no problems on the server itself, it physically crashes technic out.

**Modpack Name:** *(Only if public)*
Tekkit Legends

**Thermos Version:**
Thermos 1614 Build 50

**Comment by Rubbertjuh** [comment] 2016-03-21 17:46
Getting multiple reports from players crashing with that error as well. Running build 50 as well.

**Comment by Robotia** [comment] 2016-03-21 21:52
Did this occur in 49?

**Comment by djoveryde** [comment] 2016-03-21 21:57
I don't believe so, certainly had no one come to me about it.
Not sure if @Rubbertjuh can confirm it only started in 50?

**Comment by Robotia** [comment] 2016-03-21 22:10
Oh...actually I remember this problem. It is Tekkit Legends specific and caused by invalid Garage Doors in the Carpenter's Blocks mod.
I used to have it even when I was running KCauldron, it is definitely not caused by anything recent.

Source code needs work to fix this problem.

Closing this issue.

**Closed by Robotia** 2016-03-21 22:10 UTC
